### DISCUSSION TITLE
Initial thoughts on Many Notes

### DISCUSSION THREAD

**Discussion by Drallas** [brufdev/many-notes#18] [General]
I came across the app on Noted.lol and decided to give it a try. Some feedback to help improve the experience:

- Please enhance the Docker deployment process by not requiring a Dockerfile. Building the app takes several minutes, and it would be more efficient if the necessary permissions could be set inside the image itself.

- It would also be really helpful if the initial database could be pre-filled with some example or template data, making it easier for users to get started right away.

Looking forward to seeing how it develops.

**Comment by brufdev** [comment]
First of all, thank you for your feedback!

> Please enhance the Docker deployment process by not requiring a Dockerfile. Building the app takes several minutes, and it would be more efficient if the necessary permissions could be set inside the image itself.

Unlike many Docker images that run with root privileges, my image runs with an unprivileged user. This is better for security reasons but introduces permissions issues. With Docker Volumes, Docker handles permissions, and the `Dockerfile` isn't needed. However, based on feedback, I've changed the instructions to use bind mounts for easier maintenance. With bind mounts, permissions need to be handled during the build phase to ensure the webserver has access to the application and the mounted directories. I understand this adds an extra step, but I prefer to release the images with an unprivileged user, and for now, this is the simplest way I've found. I will continue to look for improvements, so the instructions may also change in the future.

> It would also be really helpful if the initial database could be pre-filled with some example or template data, making it easier for users to get started right away.

This could actually be a good idea. For users like myself, who already have existing notes from other applications, we only need to zip the folders, import in the vaults page, and go from there. However, for new users starting from scratch, it might be challenging to get things going.

**Comment by Drallas** [comment]
I’m really looking forward to a version of Many Notes with preloaded!

Regarding the Docker deployment. It might be better to align the Docker Deployment with how [LinuxServer.io](https://docs.linuxserver.io/misc/non-root/) handles it, using unprivileged users. Their approach doesn’t require building the final layer to bake in user permissions at runtime, which makes things much smoother for users.

As someone who’s used to working with Docker images from LinuxServer.io, I typically see a docker-compose.yml structured in this way:

```
services:
  many-notes:
    container_name: many-notes
    image: brufdev/many-notes:latest
    restart: unless-stopped
    env_file:  
      - .env  # Loads PUID and PGID from .env  
    environment:
      PUID: ${PUID}  
      PGID: ${PGID}  
    volumes:
      - many-notes:/var/www/html # Single volume for all app data
      // - ${PWD}/data:/var/www/html # Or Bind mount for all app data
    ports:
      - 80:8080
    security_opt:
      - no-new-privileges:true  # Security setting to prevent privilege escalation

volumes:
  many-notes:
    name: many-notes
```  

In its current form, Many Notes might be a bit tricky to run via platforms like Portainer (without CI/CD), or for CasaOS, and other user-friendly container runtime's. A more streamlined setup would make it easier for more users to get up and running quickly, especially with these platforms in mind.
