### ISSUE TITLE
Unable to connect to the database

### ISSUE THREAD

**Issue by rubenssoto** [brufdev/many-notes#10]
Hey, sorry for one more issue.

Probably I did something wrong.

many-notes-1  |    INFO  Configuration cache cleared successfully.  
many-notes-1  | 
many-notes-1  | ⚡️ Attempting database connection...
many-notes-1  | Waiting on database connection, retrying... 30 seconds left
many-notes-1  | Waiting on database connection, retrying... 29 seconds left
many-notes-1  | Waiting on database connection, retrying... 28 seconds left
many-notes-1  | Waiting on database connection, retrying... 27 seconds left
many-notes-1  | Waiting on database connection, retrying... 26 seconds left
many-notes-1  | Waiting on database connection, retrying... 25 seconds left
many-notes-1  | Waiting on database connection, retrying... 24 seconds left
many-notes-1  | Waiting on database connection, retrying... 23 seconds left
many-notes-1  | Waiting on database connection, retrying... 22 seconds left
many-notes-1  | Waiting on database connection, retrying... 21 seconds left
many-notes-1  | Waiting on database connection, retrying... 20 seconds left
many-notes-1  | Waiting on database connection, retrying... 19 seconds left
many-notes-1  | Waiting on database connection, retrying... 18 seconds left
many-notes-1  | Waiting on database connection, retrying... 17 seconds left
many-notes-1  | Waiting on database connection, retrying... 16 seconds left
many-notes-1  | Waiting on database connection, retrying... 15 seconds left
many-notes-1  | Waiting on database connection, retrying... 14 seconds left
many-notes-1  | Waiting on database connection, retrying... 13 seconds left
many-notes-1  | Waiting on database connection, retrying... 12 seconds left
many-notes-1  | Waiting on database connection, retrying... 11 seconds left

```
services:
  many-notes:
    image: myrepo/many-notes
    restart: unless-stopped
    environment:
      - APP_URL=https://many-notes.mydomain.com:80
      - ASSET_URL=https://many-notes.mydomain.com:80
    networks:
      - container-network
    volumes:
      - /data/apps/manynotes/database/database.sqlite:/var/www/html/database/database.sqlite
      - /data/apps/manynotes/storage-logs:/var/www/html/storage/logs
      - /data/apps/manynotes/storage-private:/var/www/html/storage/app/private
      - /data/apps/manynotes/storage-public:/var/www/html/storage/app/public
      - /data/apps/manynotes/storage-sessions:/var/www/html/storage/framework/sessions
    ports:
      - 80
networks:
  container-network:
    external: true


```

My using an nginx proxy manager as a reverse proxy.
