### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by meldarionqeusse** [brufdev/many-notes#19]
I am trying this out on a raspberrypi. Upon starting the container and trying to log into it I am getting internal server error. I made sure all files and folders are owned by uid: gid 1000:1000

```
many-notes-php-1  | 🙌 To support Server Side Up projects visit:
many-notes-php-1  | https://serversideup.net/sponsor
many-notes-php-1  |
many-notes-php-1  | -------------------------------------
many-notes-php-1  | ℹ️ Container Information
many-notes-php-1  | -------------------------------------
many-notes-php-1  |
many-notes-php-1  | OS:            Debian GNU/Linux 12 (bookworm)
many-notes-php-1  | Docker user:   www-data
many-notes-php-1  | Docker uid:    1000
many-notes-php-1  | Docker gid:    1000
many-notes-php-1  | OPcache:       ❌  Disabled
many-notes-php-1  |
many-notes-php-1  | 👉 [NOTICE]: Improve PHP performance by setting PHP_OPCACHE_ENABLE=1 (recommended for production).
many-notes-php-1  | (init-webserver-config): Processing /etc/nginx/nginx.conf.template → /etc/nginx/nginx.conf...
many-notes-php-1  | (init-webserver-config): Processing /etc/nginx/site-opts.d/http.conf.template → /etc/nginx/site-opts.d/http.conf...
many-notes-php-1  | (init-webserver-config): Processing /etc/nginx/site-opts.d/https.conf.template → /etc/nginx/site-opts.d/https.conf...
many-notes-php-1  | ℹ️ NOTICE (init-webserver-config): Enabling NGINX
site with SSL "off"...
many-notes-php-1  | [20-Feb-2025 18:26:19] NOTICE: fpm is running, pid 91
many-notes-php-1  | [20-Feb-2025 18:26:19] NOTICE: ready to handle connections
many-notes-php-1  | ✅  NGINX + PHP-FPM is running correctly.
many-notes-php-1  | 192.168.0.141 - - [20/Feb/2025:18:26:36 +0000] "GET / HTTP/1.1" 500 1029 "-" "Mozilla/5.0 (Android 14; Mobile; rv:135.0) Gecko/135.0 Firefox/135.0" "-"
many-notes-php-1  | 192.168.0.141 - - [20/Feb/2025:18:26:38 +0000] "GET / HTTP/1.1" 500 1029 "-" "Mozilla/5.0 (Android 14; Mobile; rv:135.0) Gecko/135.0 Firefox/135.0" "-"
^CGracefully stopping... (press Ctrl+C again to force)
Aborting on container exit...
 [+] Stopping 1/1
 ✔ Container many-notes-php-1  S...                             10.4s canceled
```

**Comment by meldarionqeusse** [comment]
I thought I did include it but somehow it seems I deleted by mistake sorry.

```
services:
  php:
    build:
      context: .
      args:
        UID: 1000 # change id
        GID: 1000 # change id
    restart: unless-stopped
    volumes:
      - ./database/database.sqlite:/var/www/html/database/database.sq>
      - ./storage-logs:/var/www/html/storage/logs
      - ./storage-private:/var/www/html/storage/app/private
      - ./storage-public:/var/www/html/storage/app/public
      - ./storage-sessions:/var/www/html/storage/framework/sessions
    ports:
      - 1280:8080
    environment:
      - APP_URL=http://localhost:1280
      - ASSET_URL=http://localhost:1280

```
