### ISSUE TITLE
Tried to upload PNG images but get 500 error

### ISSUE THREAD

**Issue by FurmanSK** [brufdev/many-notes#3]
Getting a 500 error on uploading a PNG image. 

Could it be possible to just drag drop into the note directly to include photos?

**Comment by brufdev** [comment]
I tested uploading a PNG image here, and it's working without errors. What version are you using? Did you upgrade from previous version or it's the first install? Do you have errors uploading any file?

Paste your compose.yaml file here, please. Just remove the passwords.

**Comment by brufdev** [comment]
> Could it be possible to just drag drop into the note directly to include photos?

Right now, adding a photo takes two steps: you have to upload it and then insert it. I agree that it should be just one step. I plan to make this change, but I need to work on some other features first to get ready for it.

**Comment by FurmanSK** [comment]
I just get 500 error. 

```
php-1  | 10.10.0.4 - - [13/Jan/2025:16:57:02 +0000] "POST /livewire/update HTTP/1.1" 200 555 "http://server:8085/vaults/1?file=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0" "-"
php-1  | 2025/01/13 16:57:02 [warn] 164#164: *20092 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000003, client: 10.10.0.4, server: _, request: "POST /livewire/upload-file?expires=1736787722&signature=052a29478d0cbfb7df9cceab8da92c22854ef2fe36a67e1082f0012d665abe79 HTTP/1.1", host: "server:8085", referrer: "http://server:8085/vaults/1?file=1"
php-1  | 10.10.0.4 - - [13/Jan/2025:16:57:02 +0000] "POST /livewire/upload-file?expires=1736787722&signature=052a29478d0cbfb7df9cceab8da92c22854ef2fe36a67e1082f0012d665abe79 HTTP/1.1" 200 103 "server:8085/vaults/1?file=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0" "-"
php-1  | 10.10.0.4 - - [13/Jan/2025:16:57:02 +0000] "POST /livewire/update HTTP/1.1" 500 6622 "http://server:8085/vaults/1?file=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0" "-"
```

This is all shows up in docker logs when trying to upload. Also, it creates a empty file too but yeah runs into an error uploading it. 

My docker compose file. I changed passwords and also the port to listen on outside so as to not conflict with other services.

```
services:
  php:
    image: brufdev/many-notes:latest
    restart: unless-stopped
    environment:
      - DB_CONNECTION=mariadb
      - DB_HOST=many-notes-mariadb-1
      - DB_PORT=3306
      - DB_DATABASE=manynotes
      - DB_USERNAME=user
      - DB_PASSWORD=*** # change password
    volumes:
      - storage-public:/var/www/html/storage/app/public
      - storage-private:/var/www/html/storage/app/private
      - storage-sessions:/var/www/html/storage/framework/sessions
      - storage-logs:/var/www/html/storage/logs
    ports:
      - 8085:8080
  mariadb:
    image: mariadb:11.6
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=***# change password
      - MARIADB_DATABASE=manynotes
      - MARIADB_USER=user
      - MARIADB_PASSWORD=*** # change password
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  storage-public:
  storage-private:
  storage-sessions:
  storage-logs:
  mariadb-data:
```
