### ISSUE TITLE
[BUG] - Issue when deploying with docker

### ISSUE THREAD

**Issue by stpnwf** [brufdev/many-notes#37]
I am running into this issue when deploying it with docker

https://github.com/user-attachments/assets/b9e70187-892e-4a3d-ad2d-20f79cd97326

This is the compose file I used

```
name: ManyNotes
services:
  ManyNotes:
    image: brufdev/many-notes:latest
    cpu_shares: 90
    command: []
    container_name: ManyNotes
    deploy:
      resources:
        limits:
          memory: 1024M
    environment:
      - APP_URL=http://localhost:6642
      - ASSET_URL=http://localhost:6642
      - TZ=Etc/UTC
      - USER_ID=1000
      - GROUP_ID=1000
    ports:
      - target: 8080
        published: "6642"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/ManyNotes/database
        target: /var/www/html/database/sqlite
      - type: bind
        source: /DATA/AppData/ManyNotes/logs
        target: /var/www/html/storage/logs
      - type: bind
        source: /DATA/AppData/ManyNotes/private
        target: /var/www/html/storage/app/private
      - type: bind
        source: /DATA/AppData/ManyNotes/public
        target: /var/www/html/storage/app/public
      - type: bind
        source: /DATA/AppData/ManyNotes/sessions
        target: /var/www/html/storage/framework/sessions
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
    hostname: ManyNotes
```
