### ISSUE TITLE
500 Server Error uploading ZIP

### ISSUE THREAD

**Issue by janaxhell** [brufdev/many-notes#4]
As told on reddit, using :latest build and setting all the env variables, as soon as I upload a 188 Mb ZIP, I see the green bar filling, then a big 500 SERVER ERROR message appears. A vault with the ZIP name is created, but it's empty.

This is my compose

```
services:
  php:
    image: brufdev/many-notes:latest
    restart: unless-stopped
    environment:
      - DB_CONNECTION=mariadb
      - DB_HOST=many-notes-mariadb-1
      - DB_PORT=3306
      - DB_DATABASE=manynotes
      - DB_USERNAME=xxxxxxxxxxx
      - DB_PASSWORD=xxxxxxxxxxxxxx # change password
      - APP_URL=http://192.168.1.164:5632
      - ASSET_URL=http://192.168.1.164:5632
      - APP_TIMEZONE=Europe/Rome
    volumes:
      - /srv/dev-disk-by-uuid-8998116d-e145-4319-8c9f-41609747f657/Configs/many-notes/storage-public:/var/www/html/storage/app/public
      - /srv/dev-disk-by-uuid-8998116d-e145-4319-8c9f-41609747f657/Configs/many-notes/storage-private:/var/www/html/storage/app/private
      - /srv/dev-disk-by-uuid-8998116d-e145-4319-8c9f-41609747f657/Configs/many-notes/storage-sessions:/var/www/html/storage/framework/sessions
      - /srv/dev-disk-by-uuid-8998116d-e145-4319-8c9f-41609747f657/Configs/many-notes/storage-logs:/var/www/html/storage/logs
    ports:
      - 5632:8080
  mariadb:
    image: mariadb:11.6
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=xxxxxxxxx # change password
      - MARIADB_DATABASE=manynotes
      - MARIADB_USER=xxxxxxxxx
      - MARIADB_PASSWORD=xxxxxxxxx # change password
    volumes:
      - /srv/dev-disk-by-uuid-8998116d-e145-4319-8c9f-41609747f657/Configs/many-notes/mariadb-data:/var/lib/mysql
      
networks:
  default:
    external:
      name: omv2b
```

**Comment by brufdev** [comment]
Thank you, now I see where is the issue.

**Comment by brufdev** [comment]
Thank you, now I see where the issue is. There are two ways to share data with containers: docker volumes and bind mounts. You are using bind mounts but you should use docker volumes. I'll try to explain why.

When you use `/path/from/host:/path/from/container`, that path from the host will be mounted in the container, but with the IDs from the host. Because bind mounts use host IDs, it can cause permission problems if the container runs with different user IDs. While you can pass host IDs to the container, it doesn’t always solve the issue because other files will still have image IDs.

Docker volumes automatically manage permissions and keep data even if you stop or remove containers, which is why I recommended them.

Check this page from Docker, as it likely explains it better: https://docs.docker.com/engine/storage/volumes/

I used to use bind mounts too, but I’ve switched to Docker volumes. Do you really need to use bind mounts?

**Comment by janaxhell** [comment]
Yes, I'm using binds everywhere and I'm not going to use volumes. I run my services on Open Media Vault which by default expects to have 2 drives, and I always use the second as /config . I know I can deviate the whole docker to that drive, but not all services are happy with that and/or it happened in the past that when I tried, it was reset to first drive after a random OMV update, breaking everything. Besides that, I want to be able to access plain /config (and /data) files, not to tinker with monolithic volumes. I am running about 150 services on 3 different machines, all using binds. If there's no way to use many-notes with binds, I'm done. But no problem, eh! It's ok, other people prefer volumes. :)

**Comment by brufdev** [comment]
Yes, I understand. At least now I know what's happening. I will test to see if it works with bind mounts because eventually others will have this same issue.

**Comment by brufdev** [comment]
I believe I found a way of working with bind mounts. My image runs with an unprivileged user to be more secure, and the only way to change the IDs is on build stage. Follow these steps:

First, in the same folder as your `compose.yaml`, create a file named `Dockerfile` containing:

```
FROM brufdev/many-notes:latest

USER root

ARG UID
ARG GID

RUN docker-php-serversideup-set-id www-data $UID:$GID && \
    docker-php-serversideup-set-file-permissions --owner $UID:$GID --service nginx

USER www-data
```

Next, in your `compose.yaml`, replace:

```yaml
    image: brufdev/many-notes:latest
```

with:

```yaml
    build:
      context: .
      args:
        UID: 1000
        GID: 1000
```

Make sure to update UID and GID with your host user IDs. Finally, run docker compose up -d. This will maintain the container's security while allowing access to your bind mounts. Let me know if this solves your problem so I can update the instructions.
