### ISSUE TITLE
Error starting the container

### ISSUE THREAD

**Issue by superfunk2000** [brufdev/many-notes#41]
The container aborts when attempting to start.

```
many-notes  | -------------------------------------
many-notes  | ℹ️ Container Information
many-notes  | -------------------------------------
many-notes  | 
many-notes  | OS:            Debian GNU/Linux 12 (bookworm)
many-notes  | Docker user:   www-data
many-notes  | Docker uid:    33
many-notes  | Docker gid:    33
many-notes  | OPcache:       ✅ Enabled
many-notes  | PHP Version:   8.4.6
many-notes  | Image Version: v3.5.2-14589891779
many-notes  | 
many-notes  | (init-webserver-config): Processing /etc/nginx/nginx.conf.template → /etc/nginx/nginx.conf...
many-notes  | (init-webserver-config): Processing /etc/nginx/site-opts.d/http.conf.template → /etc/nginx/site-opts.d/http.conf...
many-notes  | (init-webserver-config): Processing /etc/nginx/site-opts.d/https.conf.template → /etc/nginx/site-opts.d/https.conf...
many-notes  | ℹ️ NOTICE (init-webserver-config): Enabling NGINX site with SSL "off"...
many-notes  | Checking for Laravel automations...
many-notes  | 🚀 Clearing Laravel cache before attempting migrations...
many-notes  | 
many-notes  |    INFO  Configuration cache cleared successfully.  
many-notes  | 
many-notes  | ⚡️ Attempting database connection...
many-notes  | ✅ Database connection successful.
many-notes  | 🚀 Running migrations...
many-notes  | 
many-notes  | In StreamHandler.php line 156:
many-notes  |                                                                                
many-notes  |   The stream or file "/var/www/html/storage/logs/laravel.log" could not be op  
many-notes  |   ened in append mode: Failed to open stream: Permission denied                
many-notes  |   The exception occurred while attempting to log: Database file at path [/var  
many-notes  |   /www/html/database/sqlite/database.sqlite] does not exist. Ensure this is a  
many-notes  |   n absolute path to the database. (Connection: sqlite, SQL: select exists (s  
many-notes  |   elect 1 from sqlite_master where name = 'migrations' and type = 'table') as  
many-notes  |    "exists")                                                                   
many-notes  |   Context: {"exception":{"errorInfo":null,"connectionName":"sqlite"}}    
```

My Docker-compose.yaml:
```
services:
  php:
    image: brufdev/many-notes:latest
    restart: unless-stopped
    container_name: many-notes
    volumes:
      - ./data/database:/var/www/html/database/sqlite
      - ./data/storage-logs:/var/www/html/storage/logs
      - ./data/storage-private:/var/www/html/storage/app/private
      - ./data/storage-public:/var/www/html/storage/app/public
      - ./data/storage-sessions:/var/www/html/storage/framework/sessions
    ports:
      - 31821:8080
    environment:
      - APP_URL=http://myhost.mydomain.de:31821
      - ASSET_URL=http://myhost.mydomain.de:31821
      - APP_TIMEZONE=Europe/Berlin
```

The directories under ./data are created, but they are all empty.
Is this a bug or am I doing something wrong?
